### ISSUE TITLE
Feature request: flexibility in choosing the REST client implementation 

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#10]
Hi Etienne, 

We would like to have the flexibility into choosing the REST client implementation. 
The reasons for request are as follows:
- It would enable users the freedom to choose the external dependencies (an alternative to spring-boot-starter-jersey)
- It would enable users to implement fault tolerance for remote communication. 
 
Regards,
Amelia

**Comment by Mighty683** [comment]
+1 for this feature request, it would be ideal if user would be able to decide which parts of code can be generated. For example in my case I have dropwizard application where Graphql is only one endpoint and I only need to use some of parts of generated code. Finally I decided to use other package because it has better suit for my case
https://github.com/kobylynskyi/graphql-java-codegen

**Comment by etienne-sf** [comment]
Thanks for this feedback


Please note that the original message is one year old.
The client app is now a Spring app, which lets you choose have a full control on the http (and more) configuration.


Can you precise which part of generated code you would need, and which part you would not need ?

Etienne

**Comment by Mighty683** [comment]
Sorry I mistook server with client application I meant server code generation.

**Comment by etienne-sf** [comment]
No problem and thanks for the report anyway. 

I'd be interested in knowing what you would like to generate, and you would like to not generate. 

Étienne
