### ISSUE TITLE
Security vulnerability in Apache commons-text 1.9

### ISSUE THREAD

**Issue by nictas** [graphql-java-generator/graphql-maven-plugin-project#156]
Apache commons-text has the following security vulnerability and users are suggested to upgrade to 1.10:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42889

Could you please release a new version of this project with the updated version?

**Comment by etienne-sf** [comment]
Hello

I upgraded both commons-text et graphql-java to their last version.
The project build ok, so I'll release a new version soon.

In the meantime, you can add commons-text in its last version in your project (with either Gradle or Maven), so that your application doesn't use a vulnerable library.

Etienne

**Comment by etienne-sf** [comment]
Released in the 1.18.8 version
