### ISSUE TITLE
Use of lombok in generated client POJOs

### ISSUE THREAD

**Issue by paulmchugh777** [graphql-java-generator/graphql-maven-plugin-project#22]
Hi Etienne,

Do you think it would be a useful feature to be able to configure the client mode to generate POJOs using lombok annotations?

That way we could have builder classes generated for all the POJOs for free.

It would need to be a configuration point in the plugin as clients may or may not be using lombok.

If you think this is a useful feature, I would be prepared to contribute.

Paul

**Comment by etienne-sf** [comment]
I'd like to allow more way for the "user" (developper atually) to personnalize the way classesare generated.
But I want to be sure that it's simple and stable.
And it must work for both the client and the server side.

I initially wanted to let the user define his/her own velocity templates. Which implies that the data sent by the plugin to the template are really stable.


So yes, it's interesting. 

And I'm happy that there are other contributors, of course !


But here, I'd like that things are thought around, before starting coding.

I suggest to do it the AWS way : we first write the user's doc.
When we're happy with that, we'll develop the stuff.

Are you happy with that?

Etienne

**Comment by etienne-sf** [comment]
Hum, your question was simpler: just add lombok annotation.

With Lombok, you need to update your IDE configuration, so that it can compile with lombok being activated.
I think it's a bad idea to make lombok being a mandatory dependency in the generated code, and all the plugin user's IDE. It's too much constraint . 

The use of the plugin MUST only be an help. And add at least constraints as possible.

Adding builder is probably a good idea.
IMHO, the good way to do it is to update the velocity templates, without needing any constraint for the plugin user.

Etienne

**Comment by etienne-sf** [comment]
The PR is merged in the code.
We'll close this issue when I do the next release, which should be very soon.

**Comment by etienne-sf** [comment]
This PR has been merged and released.

But there is no documentation yet.

Could you add a page in the project site ?

The path in the project is:
graphql-maven-plugin-project\src\site

If you're not familiar with maven site, just send me a  MarkDown page, and I'll integrate it.
